Feature/pegout guard 20191203
cryptogarageinc/cfd-core pull request #12
Opened 2019-12-04 06:21 UTC by k-matsuzawa

## 関連Issue

- https://app.zenhub.com/workspaces/cfd-5cdbe88f0f84751dcd8fd7ab/issues/cryptogarageinc/btclib-sandbox/1006
- https://app.zenhub.com/workspaces/cfd-5cdbe88f0f84751dcd8fd7ab/issues/cryptogarageinc/btclib-sandbox/1004

## 概要

- 1006: pegoutのliquidv1制限対応
  - core:
    - pegoutのliquidv1制限追加 (elements 0.18.2対応)
    - pegout関連処理のOutputDescriptor解析処理を、Descriptorクラスに差し替え
      - tweakSum計算反映不具合により、HDWallet処理＆Descriptor修正。
      - Descriptorのマスターキー情報を"base"キーワードで取得できるよう修正。
  - cfd: パラメータにelements_net_type追加。
  - js: パラメータにelementsNetwork追加。テスト追加＆修正
- 1004: dynafed対応
  - core: 実装とテスト修正
  - js: テスト修正
- 他
  - sandbox: npm scripts修正 (winからはgo_test外した。デフォルトがmsvcなので)

## 使い方

```bash
npm run check_all
```

## 今回保留した項目とTODO

- 

## 確認項目

**PRを出した人**

- [x] チェックスクリプトでチェックを実施した 
- [x] 正常にビルドできた
- [x] 関連チケットに実績をつけた
- [x] ZenHubでPRとIssueを関連付けた
- [x] ZenHubのIssueを `Review/QA` Pipelineに移した

**レビューする人**

- [ ] 関連チケットにレビュー実績をつけた

## 備考

2019-12-04 11:22 UTC, fujita-cg commented on include/cfdcore/cfdcore_elements_transaction.h
> +   * @param[in] descriptor_derive_address  descriptor derive address.
(Memo)
param[out]へ修正

2019-12-04 11:23 UTC, fujita-cg commented on include/cfdcore/cfdcore_elements_transaction.h
> +   * @param[in] base_ext_pubkey       base extkey
(Memo)
param[out]へ修正

2019-12-05 07:14 UTC, fujita-cg requested changes
1件修正依頼があります。
（Request Changeが出ていなかったため、再度レビューコメント出しました。）

2019-12-05 07:59 UTC, fujita-cg requested changes
1件修正依頼があります。

2019-12-05 07:59 UTC, fujita-cg commented on src/cfdcore_elements_transaction.cpp
> +      xpub_str = "pkh(" + xpub_str + ")";
xpub_strはこれ以降使われていないように見えます。
不必要だと思っておりますが、不必要であれば削除をお願いします。

2019-12-05 08:02 UTC, fujita-cg commented on include/cfdcore/cfdcore_elements_transaction.h
> +   * @param[in] descriptor_derive_address  descriptor derive address.
修正 309e9cf

2019-12-05 08:02 UTC, fujita-cg commented on include/cfdcore/cfdcore_elements_transaction.h
> +   * @param[in] base_ext_pubkey       base extkey
修正 309e9cf

2019-12-05 10:02 UTC, k-matsuzawa commented on src/cfdcore_elements_transaction.cpp
> +      xpub_str = "pkh(" + xpub_str + ")";
・・・やらかしました。実装ミスですので修正します。。
`desc = Descriptor::Parse(xpub_str);` にし忘れていた。。

2019-12-05 10:27 UTC, k-matsuzawa commented on src/cfdcore_elements_transaction.cpp
> +      xpub_str = "pkh(" + xpub_str + ")";
修正しました！

2019-12-05 11:44 UTC, fujita-cg commented on src/cfdcore_elements_transaction.cpp
> +      xpub_str = "pkh(" + xpub_str + ")";
確認しました なるほどです
子鍵なので..
意図を理解していませんでした

2019-12-05 11:44 UTC, fujita-cg approved these changes

2019-12-05 11:59 UTC, merged